title: My Professional Profile Site
author: Tim Anema
job-title: Staff Software Developer
location: Toronto
description: I love building software, especially unusual software. You can often find me in the dustiest parts of your codebase, cleaning out the cobwebs.
links:
  Github: https://github.com/tanema
  Linkedin: https://linkedin.com/in/timanema
  Resume: https://www.dropbox.com/scl/fi/inrzpamde8lna4lz138u4/Resume.pdf
  Email: mailto:timanema@gmail.com
